##
# ShelfSlide Configuration
# This file is used for the configuration of the application
##

books:
  dir: "books" # directory where books.json is stored
  git: false # if true, books.json will be fetched from a git repository
slideshow:
  interval: 600 # interval between slides in s
  mode: "asc" # rand, asc (date), desc (date)
display:
  com: "spi" # spi (e-ink), hdmi (every other monitor)
  height: 800 # pixels
  width: 480 # pixels
  color: "BW" # BW, RBW, RYBW,7col
  type: "epd7in5_V2"
  rot_inv: false
